### ISSUE TITLE
Preformatted blocks on BioSQL and SeqIO pages

### ISSUE THREAD

**Issue by peterjc** [peterjc/peterjc.github.io#4]
Display of SQL "show tables" on https://peterjc.github.io/wiki/BioSQL.html / https://github.com/peterjc/peterjc.github.io/blob/master/wiki/BioSQL.md lacks line breaks, messing up the visual impression - compare with https://biopython.org/wiki/BioSQL.html

Display of a FASTA file snippet (after "The resulting Fasta file looks like this") on https://peterjc.github.io/wiki/SeqIO.html / https://github.com/peterjc/peterjc.github.io/blob/master/wiki/SeqIO.md lacks the (vital) line breaks - compare with https://biopython.org/wiki/SeqIO.html

The problem is what MediaWiki terms "Preformatted text" where each line starts with a space: http://www.mediawiki.org/wiki/Help:Formatting

Test case:
* https://github.com/peterjc/peterjc.github.io/blob/preformatting/preformatted.mediawiki
* https://github.com/peterjc/peterjc.github.io/blob/preformatting/preformatted.md

Unclear how to map MediaWiki performatted block to GitHub Flavoured Markdown (GFM). Note that how line breaks are handled is one of the differences in GFM to plain markdown.

Adding explicit ``<br />`` tags works quite well, but does not give any block-level visual styling (which MediaWiki did give us and was the purpose in picking this markup):
* https://github.com/peterjc/peterjc.github.io/blob/preformatting/preformatted_alt.md

Leaving blank lines in the raw markdown results in vertically separated lines, not great:
* https://github.com/peterjc/peterjc.github.io/blob/preformatting/preformatted_alt2.md

Using a GFM literal block fails to render any markup like italics etc, so that won't do *in general* (it should be fine for the Biopython wiki pages where I noticed the conversion problem):
* https://github.com/peterjc/peterjc.github.io/blob/preformatting/preformatted_alt3.md

The best idea I've had so far (*for general usage*) is to combine a block quote with manual line breaks:
* https://github.com/peterjc/peterjc.github.io/blob/preformatting/preformatted_alt4.md

**Comment by peterjc** [comment]
Logged with pandoc in case they can fix this https://github.com/jgm/pandoc/issues/1993

**Comment by zudov** [comment]
@petrjc I didn't want to continue discussion in pandoc's issue.

Just wanted to ask, did you try using other markup formats for README ? According to [this](https://github.com/github/markup#markups) github can render the mediawiki by itself.

**Comment by peterjc** [comment]
@zudov yes, but there is a wider context to this - migration from MediaWiki to a GitHub Pages/Jekyll website (on github.io with a custom domain to follow) driven by Markdown files hosted on GitHub. Sadly GitHub Pages/Jekyll *only* works with markdown as input. See: https://help.github.com/articles/using-jekyll-with-pages/ and https://github.com/peterjc/mediawiki_to_git_md

Right now I am dumping ``example.mediawiki`` into this git repository (on the master branch), and converting that to ``example.md`` with pandoc, which in turn is rendered as ``example.html`` using GitHub Pages/Jekyll.  Checking the mediawiki files into git is just a diagnostic tool while I sort out remaining issues in what is intended to be a one off conversion.

Thus far the GitHub rendering of each ``example.mediawiki`` is very close to the original wiki page. There are still a few problems with the GitHub rendering of the matching ``example.md`` though (which seems to be consistent with the matching ``example.html``).

e.g. https://biopython.org/wiki/BioSQL.html --> https://github.com/peterjc/peterjc.github.io/blob/master/wiki/BioSQL.mediawiki --> https://github.com/peterjc/peterjc.github.io/blob/master/wiki/BioSQL.md --> https://peterjc.github.io/wiki/BioSQL.html

**Comment by zudov** [comment]
I see. Thanks for detailed response.

**Comment by peterjc** [comment]
Will now try ``markdown_github-hard_line_breaks`` as the pandoc output format...

**Comment by peterjc** [comment]
Confirmed - Fixed using https://github.com/peterjc/mediawiki_to_git_md/commit/aa8529195abdd67872a992e15c7193e9165d65b8
